---
title: "Alzheimer Sample Chromatogram"
output: 
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Alzheimer Study", 
                href: "http://18.220.28.175/alzheimer/R/index.Rmd", 
                align: left }
runtime: shiny 
---

```{r}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly', 'DT',
         'ggthemes','ggplot2','ggthemr')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list = ls())
# setwd("/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Alzheimer_Disease_Study/R/")
load("../Rdata/psz_precalc.Rdata")
```

```{r}
inputPanel(
    selectInput("samples", "Select a Sample:", multiple = TRUE,
                choices = names(curves), selected = names(curves)[1]),
    checkboxInput("show_fractions","Show Fractions",
                  value=FALSE),
    downloadButton("download", "Download")
)
output$download = downloadHandler(
    filename = "alzheimer_pilot_sample_auc.csv",
    content = function(file){
        file.copy("../alzheimer_pilot_sample_auc.csv", file)
    }
)
```

Column 
-------------------------------------

### AUC of Fractions

```{r}
datatable(auc) %>%
    formatRound(columns = colnames(auc), digits=3)
```

Column 
-------------------------------------

### plot

```{r}
renderPlotly({
    data = NULL
    for(sample in input$samples){
        sample_data = mutate(curves[[sample]], sample = sample)
        data = rbind(data, sample_data)
    }
    max = max(data$int)
    fractions = data.frame(
        vol = sapply(1:9, function(i){
            mean(sapply(fracs[input$samples], function(xx){
                return(xx$vol[i+1])
                }))
            }),
        height = max + max/10
    )
    g = ggplot(data = data, aes(x = vol, y = int)) +
        geom_line(aes(color = sample), size=1)
    if(input$show_fractions == TRUE){
        g = g + geom_vline(data=fractions, 
                           aes(xintercept = vol), linetype="dashed",
                           col = "gray40") +
            geom_text(data = fractions[-1,],aes(x=(vol-0.5), y=height,
                           label=as.character(1:8)))
    } 
    g = g + theme_bw() +
        labs(x = "Elution Volumn (ml)", y = "Intensity") +
        theme(
            legend.position = "none",
            panel.border = element_rect(size=1, color = "black"),
            axis.title = element_text(size=13),
            axis.text = element_text(size=10)
            )
    ggplotly(g)
})
```