---
title: "Glycopeptides vs Age Scatterplot"
output: 
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Alzheimer Study", 
                href: "http://18.220.28.175/alzheimer/R/index.Rmd", 
                align: left }
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly','DT','data.table',
         'limma','ggthemes','ggplot2','ggthemr', 'matrixStats')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list=ls())
# setwd("/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Alzheimer_Disease_Study/R/visual")
load("../Rdata/glc_precalc.Rdata")
```

```{r}
inputPanel(
    selectInput("level", "Peptide or Glycan? ",
                choices = names(glycopeptide), selected = "glycans")
)
```

Column 
-------------------------------------
    
### Scatterplot

```{r}
renderPlotly({
    edata = glycopeptide[[input$level]]$edata
    pdata = glycopeptide[[input$level]]$pdata
    data = data.frame(
        Intensity = as.numeric(edata[feature_selected(),]),
        Group = pdata$GROUP,
        Age = pdata$AGE,
        Sex = pdata$SEX
    )
    p = ggplot(data, aes(x = Age, y = Intensity)) +
        geom_point(aes(color = Group, Sex=Sex), size=rel(2)) +
        stat_smooth(method='lm', formula = y~x) +
        labs(
            x="Age",
            y=input$feature
        )+
        theme_bw() +
        theme(
            legend.position = "none"
        )
    ggplotly(p, tooltip="all")
})
```

Column 
-------------------------------------
    
### stats table

```{r}
stats_table = reactive({
    age_corr[[input$level]] %>%
        setnames(c("pearson.r", "pearson.p", "spearman.r", 
                   "spearman.p", "kendall.t", "kendall.p")) %>% 
        rownames_to_column(var = "Feature") %>%
        arrange(pearson.p)  %>%
        mutate(
            pearson.r = round(pearson.r, digits = 3),
            pearson.p = round(pearson.p, digits = 3),
            spearman.r = round(spearman.r, digits = 3),
            spearman.p = round(spearman.p, digits = 3),
            kendall.t = round(kendall.t, digits = 3),
            kendall.p = round(kendall.p, digits = 3)
        ) %>%
        column_to_rownames(var = "Feature")
})
output$stats_table = renderDataTable(
    stats_table(), 
    selection = list(mode = "single", selected = 1),
    server=T
    )
feature_selected = reactive({
    rownames(stats_table())[input$stats_table_rows_selected]
})
dataTableOutput("stats_table")
```