---
title: "R Notebook"
output: 
    html_document:
        code_folding: show
        toc: true
        toc_float: true
---

```{r, include=FALSE}
options(repos = BiocManager::repositories())
library(tidyverse)
library(ggplot2)
library(HTSet)
library(lubridate)
library(limma)
library(glmnet)
library(randomForest)
library(MASS)
# library(caret)
library(performance)
# require(see)
library(ROCR)
library(pROC)
```


```{r, loading data}
data0 <- readRDS("data/serum.rds")
# set default ggplot theme
theme_set(theme_bw())
# set stringsAsFactors as FALSE by default
options(stringsAsFactors = FALSE)
```

```{r DE_function, include=FALSE}
calcDE_var <- function(datatype = "glycopeptide", formula = "~Dx_Group", coef = 3, transform = "log", cv="1"){
  data[[datatype]]$fdata$cv[is.na(data[[datatype]]$fdata$cv)] <- 1
  dataf <- subset_features(data[[datatype]], data[[datatype]]$fdata$cv<=as.numeric(cv))
  model <- model.matrix(as.formula(formula), data = dataf$pdata)
  edata <- dataf$edata[,rownames(model)]
  if(transform == "log"){
    edata <- log(edata)
  } 
  lmFit(edata, model) %>%
    eBayes() %>%
    topTable(coef = coef, number = Inf, sort.by = "none")
}
```

# Preparing Data

```{r include=FALSE}
sampleTree_pep <- hclust(dist(t(log(data0$peptide$edata))), method = "average")
plot(sampleTree_pep, main = "Peptide Sample clustering to detect outliers", sub="", 
     xlab="", cex = 0.5)
abline(h = 4, col = "red")
peptide <- subset_samples(data0$peptide, !(rownames(data0$peptide$pdata) %in% c("A9", "B10")))
```

```{r}
sampleTree_glyco <- hclust(dist(t(log(data0$glycopeptide$edata))), method = "average")
plot(sampleTree_glyco, main = "Glycopeptide Sample clustering to detect outliers", sub="", 
     xlab="", cex = 0.5)
abline(h = 15.5, col = "red")
glycopeptide <- subset_samples(data0$glycopeptide, !(rownames(data0$glycopeptide$pdata) %in% c("B10", "C13", "A67")))

sampleTree_pepi <- hclust(dist(t(log(data0$peptide_intensity$edata))), method = "average")
plot(sampleTree_pepi, main = "Peptide Intensity Sample clustering to detect outliers", sub="", 
     xlab="", cex = 0.5)
abline(h = 8, col = "red")
peptide_intensity <- subset_samples(data0$peptide_intensity, !(rownames(data0$peptide_intensity$pdata) %in% c("A9", "C13")))
```

```{r}
data <- list(peptide = peptide, glycopeptide = glycopeptide, peptide_intensity = peptide_intensity)
for (type in names(data)) {
  data[[type]]$pdata <- data[[type]]$pdata %>%
    mutate(Draw_dt = Blood_Draw_Dt) %>%
    mutate(
      years = round(time_length(interval(Draw_dt, as.POSIXct("2020-11-11",format="%Y-%m-%d")), "years")),
      days = round(as.POSIXct("2020-11-11",format="%Y-%m-%d")-Draw_dt)
    )
}
replace <- which(data$glycopeptide$pdata$adc_ethnicity == "American Indian/Alaskan Native") 
data$glycopeptide$pdata$adc_ethnicity2 <- data$glycopeptide$pdata$adc_ethnicity
data$glycopeptide$pdata$adc_ethnicity2[replace] <- NA
data$glycopeptide$pdata$adc_ethnicity2 <- droplevels(data$glycopeptide$pdata$adc_ethnicity2)
```

```{r}
set.seed(527)
glycopeptide <- data$glycopeptide %>%
    subset_samples(complete.cases(data$glycopeptide$pdata[,c("age", "adc_gender", "adc_ethnicity2", "apoe4", "bmi")]))
train_num <- sample(1:nsamples(glycopeptide),nsamples(glycopeptide)*0.65)
features <- calcDE_var("glycopeptide", "~SuperDx+age+adc_gender+adc_ethnicity2+apoe4+bmi", coef = 2) %>%
  filter(P.Value<0.05) %>%
  rownames()
# For baseline model
base <- glycopeptide$pdata[,c("SuperDx", "age", "adc_gender", "adc_ethnicity2", "apoe4", "bmi")] %>%
    mutate(SuperDx=ifelse(SuperDx=="Normal", 0, 1))
trainset_base <- base[train_num,]
testset_base <- base[-train_num,]

# For glycopeptide model
glyco <- as.data.frame(t(glycopeptide$edata)[,features]) %>%
  cbind(SuperDx = base$SuperDx)
trainset_glyco <- glyco[train_num,]
testset_glyco <- glyco[-train_num,]

# For combined model
comb <- cbind(glyco, base[, -1])
trainset_comb <- comb[train_num,]
testset_comb <- comb[-train_num,]

```


# Baseline Model

```{r}
full_logmod <- glm(SuperDx~., data = trainset_base,family = binomial())
full_logmod
summary(full_logmod)
check_cov <- check_collinearity(full_logmod)
check_cov
plot(check_cov)
# Predict the model on the test dataset
pred_logmod <- predict(full_logmod, testset_base[,colnames(testset_base)!="SuperDx"],type = "response") # transform the numeric predictive values into categorical values (use 0.5 as a threshold)
pred <- ifelse(pred_logmod>0.5, 1, 0)
# confusion matrix
logmod.conf <- table(pred,testset_base[,"SuperDx"])
logmod.conf
# classification accuracy
logmod.accuracy = ((logmod.conf[1,1]+logmod.conf[2,2])/sum(logmod.conf))
logmod.accuracy
# AUC plot
perf_log1 <- prediction(pred_logmod, testset_base[,"SuperDx"]) %>%
    ROCR::performance("tpr","fpr")
plot(perf_log1,col="#F8766D",main="ROC for Classification with Logistic Regression")
roc1 <- roc(testset_base[,"SuperDx"], pred_logmod)
# ci.auc(roc)
# plot(roc)
auc1 <- auc(testset_base[,"SuperDx"], pred_logmod)
auc1
ci.auc(auc1)

```


# Glycopeptide Model

```{r eval=FALSE, include=FALSE}
# Full model
full_logmod <- glm(SuperDx~., data = trainset_glyco,family = binomial())
full_logmod
summary(full_logmod)
check_cov <- check_collinearity(full_logmod)
check_cov
plot(check_cov)
# Predict the model on the test dataset
pred_logmod <- predict(full_logmod, testset_glyco[,colnames(testset_glyco)!="SuperDx"],type = "response") # transform the numeric predictive values into categorical values (use 0.5 as a threshold)
pred <- ifelse(pred_logmod>0.5, 1, 0)
# confusion matrix
logmod.conf <- table(pred,testset_glyco[,"SuperDx"])
logmod.conf
# classification accuracy
logmod.accuracy = ((logmod.conf[1,1]+logmod.conf[2,2])/sum(logmod.conf))
logmod.accuracy
# AUC plot
perf_log2 <- prediction(pred_logmod, testset_glyco[,"SuperDx"]) %>%
    ROCR::performance("tpr","fpr")
plot(perf_log2,col="#F8766D",main="ROC for Classification with Logistic Regression")
roc2 <- roc(testset_glyco[,"SuperDx"], pred_logmod)
(auc2 <- auc(testset_glyco[,"SuperDx"], pred_logmod))
ci.auc(auc2)

# training
best_logmod <- stepAIC(full_logmod,trace = 0) 
best_logmod
summary(best_logmod)
check_cov <- check_collinearity(best_logmod)
check_cov
plot(check_cov)
# Predict the model on the test dataset
pred_logmod <- predict(best_logmod, testset_glyco[,colnames(testset_glyco)!="SuperDx"],type = "response") # transform the numeric predictive values into categorical values (use 0.5 as a threshold)
pred <- ifelse(pred_logmod>0.5, 1, 0)
# confusion matrix
logmod.conf <- table(pred,testset_glyco[,"SuperDx"])
logmod.conf
# classification accuracy
logmod.accuracy = ((logmod.conf[1,1]+logmod.conf[2,2])/sum(logmod.conf))
logmod.accuracy
# ROC plot
perf_log3 <- prediction(pred_logmod, testset_glyco[,"SuperDx"]) %>%
    ROCR::performance("tpr","fpr")
plot(perf_log3,col="#F8766D",main="ROC for Classification with Logistic Regression")
roc3 <- roc(testset_glyco[,"SuperDx"], pred_logmod)
(auc3 <- auc(testset_glyco[,"SuperDx"], pred_logmod))
ci.auc(auc3)


# baseline model vs glycopeptide full model
roc.test(roc1, roc2, alternative = "less")
# baseline model vs glycopeptide trained model
roc.test(roc1, roc3, alternative = "less")
roc.test(roc3, roc2, alternative = "less")

data.frame(Dx=factor(testset_glyco[,"SuperDx"], labels = c("Normal", "AD")), score=pred_logmod) %>%
    ggplot(aes(x=score, fill=Dx)) +
    geom_histogram(binwidth = 0.01)

```


Use Ridge:
```{r}
x <- model.matrix(SuperDx~., trainset_glyco)[,-1] # remove the intercept
y <- trainset_glyco$SuperDx 
# check collinearity

# Ridge
# grid <- 10^seq(10, -2, length = 100)
ridge_mod <- glmnet(x, y, alpha = 0, family = "binomial")
dim(coef(ridge_mod))
plot(ridge_mod)    # Draw plot of coefficients

```

Cross validation with the `cv.glmnet()` function.
```{r}
set.seed(1)
cv.out <- cv.glmnet(as.matrix(trainset_glyco[,1:24]), trainset_glyco[,25], alpha = 0, family = "binomial", type.measure = "auc") # Fit binomial regression model on training data
bestlam <- cv.out$lambda.min  # Select lambda that maximizes training AUC
bestlam
plot(cv.out)
```
use the best $\lambda$ selected by cv.
```{r}
out <- glmnet(as.matrix(trainset_glyco[,1:24]), trainset_glyco[,25], alpha = 0, family = "binomial") # Fit ridge regression model on full dataset
predict(out, type = "coefficients", s = bestlam) # Display coefficients using lambda chosen by CV
```

Make prediction and calculate AUC.
```{r}
# Predict the model on the test dataset
pred_logmod <- predict(out, as.matrix(testset_glyco[,1:24]),s = bestlam, family = "binomial", type = "response") 
# transform the numeric predictive values into categorical values (use 0.5 as a threshold)
pred <- ifelse(pred_logmod>0.5, 1, 0)
# confusion matrix
logmod.conf <- table(pred,testset_glyco[,"SuperDx"])
logmod.conf
# classification accuracy
logmod.accuracy = ((logmod.conf[1,1]+logmod.conf[2,2])/sum(logmod.conf))
logmod.accuracy
# ROC plot
perf_log3 <- prediction(pred_logmod, testset_glyco[,"SuperDx"]) %>%
    ROCR::performance("tpr","fpr")
plot(perf_log3,col="#F8766D",main="ROC for Classification with Logistic Regression")
roc3 <- roc(testset_glyco[,"SuperDx"], as.numeric(pred_logmod))
(auc3 <- auc(testset_glyco[,"SuperDx"], as.numeric(pred_logmod)))
ci.auc(auc3)
```

# Visulization

## ROC curve

```{r}
plot(perf_log1,col="red",main="ROC for Classification with Logistic Regression")
# plot(perf_log2,col="steelblue",add=TRUE)
plot(perf_log3,col="orange",add=TRUE)
legend(0.6, 0.3, legend = c("baseline", "glycopeptide"), col = c("red", "orange"), lty=1)
data.frame(
  model = c("baseline", "glycopeptide"),
  auc = c(auc1, auc3),
  auc_CI = c(str_c(format(as.numeric(ci.auc(auc1))[c(1,3)], digits = 4), collapse = "-"),  str_c(format(as.numeric(ci.auc(auc3))[c(1,3)], digits = 4), collapse = "-"))
)
```

## AUC comparison
```{r}
# bar plot of AUC
data.frame(
    model = c("baseline", "glyco"),
    auc = c(roc1$auc, roc3$auc),
    se = c(sqrt(var(roc1)), sqrt(var(roc3)))
) %>%
    mutate(lower = auc-se,
           upper = auc+se
           ) %>%
    ggplot(aes(x = model, y = auc))+
    geom_col(width = 0.4) + 
    geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.1)+
    theme_bw()


# baseline model vs glycopeptide full model
# roc.test(roc1, roc2, alternative = "less")
# baseline model vs glycopeptide trained model
roc.test(roc1, roc3, alternative = "less")
# roc.test(roc3, roc2, alternative = "less")
```
## Score Distribution

```{r}
data.frame(Dx=factor(testset_glyco[,"SuperDx"], labels = c("Normal", "AD")), 
           score = as.numeric(pred_logmod)) %>%
    ggplot(aes(x=score, fill=Dx)) +
    geom_density(alpha=0.5)
```

# PCA Analysis  
```{r}
glycopeptide
# rows are genes, cols are samples
# use prcomp() to do PCA on the data
# prcomp() expects the samples to be rows and the genes to be columns
pca <- prcomp(t(glycopeptide$edata), scale = TRUE)

plot(pca$x[,1], pca$x[,2])
# sdev stands for "standard deviation"
# sdev^2 calculates how much variation in the original data each principle component accounts for.
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100,1)
barplot.default(pca.var.per, main="Scree Plot", xlab="Principal Component", ylab="Percent Variation")

# plot with ggplot2
pca.data <- data.frame(
  Sample = glycopeptide$pdata$adc_gender,
  X = pca$x[,1],
  Y = pca$x[,2]
)
ggplot(pca.data, aes(X, Y, color = Sample))+
  geom_point()+
  theme_bw()
```

Use the factoextra R package
```{r}
library(factoextra)
# pca is calculated above

# Scree plot
fviz_eig(pca)
```

Plot individuals.
```{r}
fviz_pca_ind(pca,
             col.ind = glycopeptide$pdata$SuperDx, # Color by the quality of representation
             repel = TRUE     # Avoid text overlapping
             )
```

Graph of variables.
```{r}
fviz_pca_var(pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,     # Avoid text overlapping
             select.var = list(contrib = 7)
             )
```

